In [74]:
import pandas as pd
import matplotlib as plt
df = pd.read_csv("csvs\\churndata.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [20]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [21]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [22]:
df.drop('customerID', axis= 1, inplace = True)
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [23]:
df['gender'].replace({'Female':1,'Male':0},inplace=True)

In [27]:
def print_unique(df):
    for col in df:
        if df[col].dtypes == 'object':
            print(f'{col} : {df[col].unique()}')

In [28]:
print_unique(df)

Partner : ['Yes' 'No']
Dependents : ['No' 'Yes']
PhoneService : ['No' 'Yes']
MultipleLines : ['No phone service' 'No' 'Yes']
InternetService : ['DSL' 'Fiber optic' 'No']
OnlineSecurity : ['No' 'Yes' 'No internet service']
OnlineBackup : ['Yes' 'No' 'No internet service']
DeviceProtection : ['No' 'Yes' 'No internet service']
TechSupport : ['No' 'Yes' 'No internet service']
StreamingTV : ['No' 'Yes' 'No internet service']
StreamingMovies : ['No' 'Yes' 'No internet service']
Contract : ['Month-to-month' 'One year' 'Two year']
PaperlessBilling : ['Yes' 'No']
PaymentMethod : ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
TotalCharges : ['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Churn : ['No' 'Yes']

In [29]:
pd.to_numeric(df.TotalCharges)

ValueError: Unable to parse string " " at position 488

In [33]:
df.iloc[488]

gender                                      1
SeniorCitizen                               0
Partner                                   Yes
Dependents                                Yes
tenure                                      0
PhoneService                               No
MultipleLines                No phone service
InternetService                           DSL
OnlineSecurity                            Yes
OnlineBackup                               No
DeviceProtection                          Yes
TechSupport                               Yes
StreamingTV                               Yes
StreamingMovies                            No
Contract                             Two year
PaperlessBilling                          Yes
PaymentMethod       Bank transfer (automatic)
MonthlyCharges                          52.55
TotalCharges
Churn                                      No
Name: 488, dtype: object

In [46]:
df1 = df[df['TotalCharges'] != ' ']
df1.TotalCharges = pd.to_numeric(df1.TotalCharges)

C:\Users\jlhb83\AppData\Local\Temp\ipykernel_17120\2833572060.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.TotalCharges = pd.to_numeric(df1.TotalCharges)

In [38]:
df1.shape

(7032, 20)

In [48]:
df1.replace('No internet service','No',inplace=True)
df1.replace('No phone service','No',inplace=True)

C:\Users\jlhb83\AppData\Local\Temp\ipykernel_17120\2045096646.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.replace('No internet service','No',inplace=True)
C:\Users\jlhb83\AppData\Local\Temp\ipykernel_17120\2045096646.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.replace('No phone service','No',inplace=True)

In [49]:
print_unique(df1)

MultipleLines : ['No' 0 1]
InternetService : ['DSL' 'Fiber optic' 0]
OnlineSecurity : [0 1 'No']
OnlineBackup : [1 0 'No']
DeviceProtection : [0 1 'No']
TechSupport : [0 1 'No']
StreamingTV : [0 1 'No']
StreamingMovies : [0 1 'No']
Contract : ['Month-to-month' 'One year' 'Two year']
PaymentMethod : ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [50]:
df1.replace({'DSL' : 'Yes', 'Fiber optic' : 'Yes'}, inplace = True)
print_unique(df1)

MultipleLines : ['No' 0 1]
InternetService : ['Yes' 0]
OnlineSecurity : [0 1 'No']
OnlineBackup : [1 0 'No']
DeviceProtection : [0 1 'No']
TechSupport : [0 1 'No']
StreamingTV : [0 1 'No']
StreamingMovies : [0 1 'No']
Contract : ['Month-to-month' 'One year' 'Two year']
PaymentMethod : ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

C:\Users\jlhb83\AppData\Local\Temp\ipykernel_17120\2060599093.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.replace({'DSL' : 'Yes', 'Fiber optic' : 'Yes'}, inplace = True)

In [51]:
df1.replace({'Yes': 1, 'No' : 0}, inplace = True)
print_unique(df1)

Contract : ['Month-to-month' 'One year' 'Two year']
PaymentMethod : ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

C:\Users\jlhb83\AppData\Local\Temp\ipykernel_17120\1844648966.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.replace({'Yes': 1, 'No' : 0}, inplace = True)

In [52]:
df2 = pd.get_dummies(data = df1, drop_first = True, dtype = float, columns = ['Contract','PaymentMethod'])
df2

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,0,1,0,0,1,0,1,...,0,1,29.85,29.85,0,0.0,0.0,0.0,1.0,0.0
1,0,0,0,0,34,1,0,1,1,0,...,0,0,56.95,1889.50,0,1.0,0.0,0.0,0.0,1.0
2,0,0,0,0,2,1,0,1,1,1,...,0,1,53.85,108.15,1,0.0,0.0,0.0,0.0,1.0
3,0,0,0,0,45,0,0,1,1,0,...,0,0,42.30,1840.75,0,1.0,0.0,0.0,0.0,0.0
4,1,0,0,0,2,1,0,1,0,0,...,0,1,70.70,151.65,1,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,24,1,1,1,1,0,...,1,1,84.80,1990.50,0,1.0,0.0,0.0,0.0,1.0
7039,1,0,1,1,72,1,1,1,0,1,...,1,1,103.20,7362.90,0,1.0,0.0,1.0,0.0,0.0
7040,1,0,1,1,11,0,0,1,1,0,...,0,1,29.60,346.45,0,0.0,0.0,0.0,1.0,0.0
7041,0,1,1,0,4,1,1,1,0,0,...,0,1,74.40,306.60,1,0.0,0.0,0.0,0.0,1.0
7042,0,0,0,0,66,1,0,1,1,0,...,1,1,105.65,6844.50,0,0.0,1.0,0.0,0.0,0.0

In [53]:
cols_to_scale = ['tenure','MonthlyCharges','TotalCharges']

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df2[cols_to_scale] = scaler.fit_transform(df2[cols_to_scale])

In [54]:
X = df2.drop('Churn',axis='columns')
y = df2['Churn']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=5)

In [55]:
df2.dtypes

gender                                     int64
SeniorCitizen                              int64
Partner                                    int64
Dependents                                 int64
tenure                                   float64
PhoneService                               int64
MultipleLines                              int64
InternetService                            int64
OnlineSecurity                             int64
OnlineBackup                               int64
DeviceProtection                           int64
TechSupport                                int64
StreamingTV                                int64
StreamingMovies                            int64
PaperlessBilling                           int64
MonthlyCharges                           float64
TotalCharges                             float64
Churn                                      int64
Contract_One year                        float64
Contract_Two year                        float64
PaymentMethod_Credit card (automatic)    float64
PaymentMethod_Electronic check           float64
PaymentMethod_Mailed check               float64
dtype: object

In [57]:
X_train.shape

(5625, 22)

In [64]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(20, input_shape = (22,), activation = 'relu'),
    keras.layers.Dense(1, activation = 'sigmoid')
])
model.compile(optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])
model.fit(X_train, y_train, epochs = 30)

Epoch 1/30
176/176 [==============================] - 0s 798us/step - loss: 0.5612 - accuracy: 0.6951
Epoch 2/30
176/176 [==============================] - 0s 770us/step - loss: 0.4570 - accuracy: 0.7883
Epoch 3/30
176/176 [==============================] - 0s 840us/step - loss: 0.4362 - accuracy: 0.7929
Epoch 4/30
176/176 [==============================] - 0s 803us/step - loss: 0.4266 - accuracy: 0.7972
Epoch 5/30
176/176 [==============================] - 0s 738us/step - loss: 0.4215 - accuracy: 0.8005
Epoch 6/30
176/176 [==============================] - 0s 791us/step - loss: 0.4185 - accuracy: 0.8032
Epoch 7/30
176/176 [==============================] - 0s 785us/step - loss: 0.4168 - accuracy: 0.8048
Epoch 8/30
176/176 [==============================] - 0s 778us/step - loss: 0.4152 - accuracy: 0.8021
Epoch 9/30
176/176 [==============================] - 0s 781us/step - loss: 0.4148 - accuracy: 0.8036
Epoch 10/30
176/176 [==============================] - 0s 772us/step - loss: 0.4131 - accuracy: 0.8080
Epoch 11/30
176/176 [==============================] - 0s 767us/step - loss: 0.4116 - accuracy: 0.8062
Epoch 12/30
176/176 [==============================] - 0s 758us/step - loss: 0.4125 - accuracy: 0.8076
Epoch 13/30
176/176 [==============================] - 0s 797us/step - loss: 0.4099 - accuracy: 0.8103
Epoch 14/30
176/176 [==============================] - 0s 789us/step - loss: 0.4092 - accuracy: 0.8121
Epoch 15/30
176/176 [==============================] - 0s 826us/step - loss: 0.4081 - accuracy: 0.8100
Epoch 16/30
176/176 [==============================] - 0s 790us/step - loss: 0.4078 - accuracy: 0.8082
Epoch 17/30
176/176 [==============================] - 0s 807us/step - loss: 0.4073 - accuracy: 0.8112
Epoch 18/30
176/176 [==============================] - 0s 806us/step - loss: 0.4063 - accuracy: 0.8128
Epoch 19/30
176/176 [==============================] - 0s 808us/step - loss: 0.4057 - accuracy: 0.8128
Epoch 20/30
176/176 [==============================] - 0s 799us/step - loss: 0.4050 - accuracy: 0.8126
Epoch 21/30
176/176 [==============================] - 0s 920us/step - loss: 0.4051 - accuracy: 0.8144
Epoch 22/30
176/176 [==============================] - 0s 804us/step - loss: 0.4042 - accuracy: 0.8103
Epoch 23/30
176/176 [==============================] - 0s 829us/step - loss: 0.4034 - accuracy: 0.8137
Epoch 24/30
176/176 [==============================] - 0s 809us/step - loss: 0.4033 - accuracy: 0.8133
Epoch 25/30
176/176 [==============================] - 0s 800us/step - loss: 0.4026 - accuracy: 0.8158
Epoch 26/30
176/176 [==============================] - 0s 803us/step - loss: 0.4025 - accuracy: 0.8165
Epoch 27/30
176/176 [==============================] - 0s 799us/step - loss: 0.4022 - accuracy: 0.8160
Epoch 28/30
176/176 [==============================] - 0s 779us/step - loss: 0.4029 - accuracy: 0.8155
Epoch 29/30
176/176 [==============================] - 0s 799us/step - loss: 0.4014 - accuracy: 0.8171
Epoch 30/30
176/176 [==============================] - 0s 817us/step - loss: 0.4010 - accuracy: 0.8188

In [65]:
model.evaluate(X_test, y_test)

44/44 [==============================] - 0s 967us/step - loss: 0.4392 - accuracy: 0.7896

[0.439164400100708, 0.7896233201026917]

In [68]:
yp = model.predict(X_test)
yp[:5]

44/44 [==============================] - 0s 670us/step

array([[0.18212904],
       [0.34371203],
       [0.00801186],
       [0.7618371 ],
       [0.4037862 ]], dtype=float32)

In [71]:
y_pred = []
for element in yp:
    if element > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [72]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.91      0.86       999
           1       0.69      0.50      0.58       408

    accuracy                           0.79      1407
   macro avg       0.75      0.70      0.72      1407
weighted avg       0.78      0.79      0.78      1407

In [76]:
import seaborn as sn
%matplotlib inline
cm = tf.math.confusion_matrix(labels=y_test,predictions=y_pred)
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

TypeError: 'module' object is not callable